version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - ./data:/var/lib/mysql/data
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./client/.env
    depends_on:
      - backend